In [ ]:
import pandas as pd
df = pd.read_pickle("data/courses.pkl")

In [3]:
df.head()

,file_name,class_id,title,instructor,location,course_type,cost_gbp,learning_objectives,provided_materials,skills_developed,description
0,class_001_The_Art_of_Wondrous_Waffle_Weaving.pdf,CLASS_4033,The Art of Wondrous Waffle Weaving,Chef Waffleby,Harrogate,Culinary Arts,75.0,[Master the technique of creating intricate wa...,"[Professional waffle iron, Selection of flours...","[Culinary Arts, Baking, Creative Cooking, Food...",Join us at the Harrogate Culinary Academy for ...
1,class_002_Cornish_Pasty_Poetry__Patisserie.pdf,CLASS_0317,Cornish Pasty Poetry & Patisserie,Chef Rhubarb Mince,Cornwall,Traditional Skills,85.0,[Master the art of crafting the perfect Cornis...,"[Organic flour and butter, Locally sourced ing...","[Cooking, Creative Writing, Cultural History, ...",Welcome to the Cornish Pasty Poetry & Patisser...
2,class_003_Mystical_Moss_Mosaics.pdf,CLASS_8879,Mystical Moss Mosaics,Professor Mossbottom Scottish,Highlands,Nature Crafts,85.0,[Identify and collect different types of moss ...,"[Moss identification booklet, Trowel, Canvas b...","[Nature Art, Botanical Knowledge, Eco-Friendly...",Venture into the enchanting wilderness of the ...
3,class_004_Advanced_Hedgehog_Husbandry.pdf,CLASS_1153,Advanced Hedgehog Husbandry,Mr. Pricklesworth,Norfolk,Traditional Skills,95.0,[Learn the basics of hedgehog care and feeding...,"[Hedgehog-friendly gloves, Illustrated hedgeho...","[Animal Care, Wildlife Conservation, Mindfulne...","Welcome to ""Advanced Hedgehog Husbandry,"" a ch..."
4,class_005_Leafy_Quill_and_Ink_Potion_Mastery.pdf,CLASS_9224,Leafy Quill and Ink Potion Mastery,Professor Ivy Fernsnap,Oxford,Nature Crafts,75.0,"[Craft quills from natural materials, Create b...","[Selection of feathers and twigs, Natural plan...","[Nature crafts, Botanical art, Writing techniq...",Join Professor Ivy Fernsnap in the historic ci...

In [4]:
df.columns

Index(['file_name', 'class_id', 'title', 'instructor', 'location',
       'course_type', 'cost_gbp', 'learning_objectives', 'provided_materials',
       'skills_developed', 'description'],
      dtype='object')

In [7]:
print(df[df['class_id'] == 'CLASS_2530'])

                                            file_name    class_id  \
12  class_013_fantastical_felted_creature_concocti...  CLASS_2530
49  class_050_cloud_gazing_and_whimsical_weather_w...  CLASS_2530

                                         title                    instructor  \
12     Fantastical Felted Creature Concoctions   Ms. Woolina Fuzzbubble Peak
49  Cloud Gazing and Whimsical Weather Writing  Professor Nimbus Cloudsworth

    location  course_type  cost_gbp  \
12  District   Fiber Arts      85.0
49    Exeter  Mindfulness      65.0

                                  learning_objectives  \
12  [Master the basics of needle felting and sculp...
49  [Understand the different types of clouds and ...

                                   provided_materials  \
12  [Assortment of colorful wool roving, Needle fe...
49  [Cloud classification guidebook, Weather obser...

                                     skills_developed  \
12  [Needle Felting, Color Blending, Creative Desi...
49  [Mindfulness, Creative Writing, Weather Observ...

                                          description
12  Join Ms. Woolina Fuzzbubble in the heart of th...
49  Join Professor Nimbus Cloudsworth in a whimsic...

In [8]:
all_duplicates = df[df.duplicated('class_id', keep=False)]

In [9]:
all_duplicates

,file_name,class_id,title,instructor,location,course_type,cost_gbp,learning_objectives,provided_materials,skills_developed,description
0,class_001_The_Art_of_Wondrous_Waffle_Weaving.pdf,CLASS_4033,The Art of Wondrous Waffle Weaving,Chef Waffleby,Harrogate,Culinary Arts,75.0,[Master the technique of creating intricate wa...,"[Professional waffle iron, Selection of flours...","[Culinary Arts, Baking, Creative Cooking, Food...",Join us at the Harrogate Culinary Academy for ...
12,class_013_fantastical_felted_creature_concocti...,CLASS_2530,Fantastical Felted Creature Concoctions,Ms. Woolina Fuzzbubble Peak,District,Fiber Arts,85.0,[Master the basics of needle felting and sculp...,"[Assortment of colorful wool roving, Needle fe...","[Needle Felting, Color Blending, Creative Desi...",Join Ms. Woolina Fuzzbubble in the heart of th...
32,class_033_pirate_pastry_plundering.pdf,CLASS_5355,Pirate Pastry Plundering,Captain Crumbbeard,Cornwall,Culinary Arts,75.0,[Master the art of baking flaky pastries with ...,"[Pirate-themed apron, Selection of spices and ...","[Baking, Pastry Design, Flavor Innovation, Mar...","Ahoy, landlubbers and aspiring pastry pirates!..."
48,class_049_the_art_of_edible_poetry_culinary_so...,CLASS_9788,The Art of Edible Poetry: Culinary Sonnet Crea...,Chef Rhymus Scone,Brighton,Culinary Arts,85.0,[Compose culinary sonnets using food ingredien...,"[Assorted fresh herbs and edible flowers, Sele...","[Culinary Creativity, Poetry Composition, Plat...",Step into the delightful world of 'The Art of ...
49,class_050_cloud_gazing_and_whimsical_weather_w...,CLASS_2530,Cloud Gazing and Whimsical Weather Writing,Professor Nimbus Cloudsworth,Exeter,Mindfulness,65.0,[Understand the different types of clouds and ...,"[Cloud classification guidebook, Weather obser...","[Mindfulness, Creative Writing, Weather Observ...",Join Professor Nimbus Cloudsworth in a whimsic...
50,class_051_medieval_banter_and_bard_building.pdf,CLASS_5726,Medieval Banter and Bard Building,Sir Lyric Lancelot,Harrogate,Traditional Skills,75.0,[Learn the art of crafting humorous limericks ...,[Feather quills and parchment for song writing...,"[Creative Writing, Performance Arts, Historica...",Step into the world of medieval merriment with...
111,class_112_enchanted_cornish_pasties_a_culinary...,CLASS_2896,Enchanted Cornish Pasties: A Culinary Journey,Chef Crumble Crustworthy,Cornwall,Traditional Skills,75.0,[Master the traditional Cornish pasty recipe w...,"[Fresh ingredients sourced locally (potatoes, ...","[Culinary Arts, Food Presentation, Cultural Hi...",Welcome to 'Enchanted Cornish Pasties: A Culin...
115,class_116_fantastical_feathered_friend_nesting...,CLASS_9788,Fantastical Feathered Friend Nesting,Professor Pippa Partridge,Edinburgh,Nature Crafts,95.0,[Understand the ecology of local bird species ...,"[Sustainable wood planks, Eco-friendly paint a...","[Woodworking, Environmental Science, Creative ...",Join Professor Pippa Partridge on a whimsical ...
116,class_117_the_art_of_gourmet_sandwich_sculptur...,CLASS_7904,The Art of Gourmet Sandwich Sculpture,Chef Baguette,Glasgow,Culinary Arts,75.0,[Master the art of bread selection and pairing...,"[Variety of artisanal bread, Selection of gour...","[Culinary Skills, Creative Cooking, Presentati...",Step into the delightful world of culinary cre...
145,class_146_quaint_quillmanship_the_art_of_feath...,CLASS_2896,Quaint Quillmanship: The Art of Feather Pen,Penelope Parchment,Durham,Traditional Skills,70.0,[Master the technique of writing with a feathe...,"[Feather quill pens, Handmade parchment paper,...","[Calligraphy, Historical Skills, Creative Writ...",Step back in time and embrace the whimsical el...
167,class_168_pirate_parrot_persuasion_the_art_of_...,CLASS_7904,Pirate Parrot Persuasion: The Art of Avian All...,Captain Tweetbeak,Suffolk,Outdoor Skills,85.0,[Understand basic parrot communication techniq...,"[Wooden perch kit, Assorted bird treats, Pirat...","[Animal Communication, Outdoor Skills, Creativ...",Join us in the heart of Suffolk for a truly un...
177,class_178_highland_gnome_gathering_with_gertie...,CLASS_4033,Highland Gnome Gathering with Gertie,Gertie McGnome Scottish,Highlands,Seasonal Activities,75.0,[Identify and appreciate various local flora a...,"[Miniature garden tools, Natural materials (st...","[Gardening, Storytelling, Crafting, Environmen...",Join Gertie McGnome for a delightful day of gn...
192,class_193_unicorn_blanket_weaving.pdf,CLASS_5355,Unicorn Blanket Weaving,Sir Weftalot Scottish,Highlands,Fiber Arts,95.0,[Master basic and advanced weaving techniques ...,"[Magic-infused looms, Assorted enchanted fiber...","[Weaving, Creativity, Pattern Design, Cultural...",Join us in the enchanting Scottish Highlands f...
207,class_208_enchanted_hedgehog_foraging_and_feas...,CLASS_5726,Enchanted Hedgehog Foraging and Feasts,Professor Pricklesworth,Harrogate,Outdoor Skills,75.0,[Identify edible wild plants and mushrooms saf...,"[Foraging basket, Recipe booklet for hedgehog-...","[Foraging, Cooking, Ecology, Artistic Presenta...",Join us in the picturesque landscapes of Harro...